spring:
  #配置数据源
  datasource:
    dynamic:
      #设置默认数据源或数据源组
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatisplusdb?serverTimezone=GMT%2B8&characterEncoding=utf-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password:
        slave_1:
          url: jdbc:mysql://localhost:3306/mybatisdb?serverTimezone=GMT%2B8&characterEncoding=utf-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password:
