spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loy_security?characterEncoding=utf-8&serverTimezone=UTC
    type: com.mysql.cj.jdbc.MysqlDataSource
    username: root
    password: root

  redis:
    client-type: lettuce
    host: 127.0.0.1
    port: 6379
    password: