spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplusdb?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #设置mybatisplus全局配置
  global-config:
    db-config:
      #设置表前缀
#      table-prefix: t_
      #设置主键自增策略
      id-type: auto
  type-aliases-package: com.loy.mybatisplus.pojo

