spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
