#设置：方式一
#spring:
#  security:
#    user:
#      name: loy
#      password: 123
spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/sp_sec?serverTimezone=GMT%2B8
    username: root
    password: root